// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_completed_200_levels = "CgkIkrOzieYREAIQBw"; // <GPGSID>
        public const string achievement_finish_tutorial = "CgkIkrOzieYREAIQAQ"; // <GPGSID>
        public const string achievement_completed_100_levels = "CgkIkrOzieYREAIQBQ"; // <GPGSID>
        public const string achievement_completed_150_levels = "CgkIkrOzieYREAIQBg"; // <GPGSID>
        public const string achievement_completed_75_levels = "CgkIkrOzieYREAIQBA"; // <GPGSID>
        public const string achievement_completed_600_levels = "CgkIkrOzieYREAIQDA"; // <GPGSID>
        public const string achievement_completed_25_levels = "CgkIkrOzieYREAIQAw"; // <GPGSID>
        public const string achievement_completed_1000_levels = "CgkIkrOzieYREAIQDg"; // <GPGSID>
        public const string achievement_completed_300_levels = "CgkIkrOzieYREAIQCQ"; // <GPGSID>
        public const string achievement_completed_750_levels = "CgkIkrOzieYREAIQDQ"; // <GPGSID>
        public const string achievement_completed_500_levels = "CgkIkrOzieYREAIQCw"; // <GPGSID>
        public const string achievement_completed_400_levels = "CgkIkrOzieYREAIQCg"; // <GPGSID>
        public const string achievement_completed_50_levels = "CgkIkrOzieYREAIQAg"; // <GPGSID>
        public const string achievement_completed_250_levels = "CgkIkrOzieYREAIQCA"; // <GPGSID>

}

