ANDROID_HOME=/Applications/Unity/Hub/Editor/2022.3.55f1/PlaybackEngines/AndroidPlayer/SDK
TARGET_DIR=/Users/omereizenberg/Documents/ArrowsMasterGit/Assets/Plugins/Android
MAVEN_REPOS=https\://maven.google.com/
PACKAGES_TO_COPY=com.unity3d.ads-mediation\:mediation-sdk\:9.2.0;com.google.android.gms\:play-services-ads-identifier\:18.1.0;com.unity3d.ads-mediation\:unityads-adapter\:5.4.0;com.unity3d.ads\:unity-ads\:4.16.5;com.applovin\:applovin-sdk\:13.5.1
USE_JETIFIER=1
DATA_BINDING_VERSION=7.4.2