using UnityEngine;
using System;
using GoogleMobileAds.Ump.Api;
using Unity.Services.LevelPlay;
using System.Collections.Generic;

namespace Assets.Scripts.Core
{
    public class ConsentManager : MonoBehaviour
    {
        public static void RequestConsent(Action onComplete)
        {
            Debug.Log("[ConsentManager] Gathering consent information...");

            var requestParameters = new ConsentRequestParameters
            {
                TagForUnderAgeOfConsent = false
            };

            // Check the current consent information status.
            ConsentInformation.Update(requestParameters, (FormError updateError) =>
            {
                if (updateError != null)
                {
                    Debug.LogError($"[ConsentManager] Consent info update failed: {updateError.Message}");
                    // Even if it fails, we should continue initializing ads so the user can play
                    SetLevelPlayPrivacyFlagsAndContinue(onComplete);
                    return;
                }

                // If the error is null, the consent information state was updated.
                // You are now ready to check if a form is available.
                ConsentForm.LoadAndShowConsentFormIfRequired((FormError showError) =>
                {
                    if (showError != null)
                    {
                        Debug.LogError($"[ConsentManager] Error showing consent form: {showError.Message}");
                    }
                    else
                    {
                        Debug.Log("[ConsentManager] Consent form shown or not required.");
                    }

                    // Consent has been gathered (or bypassed/failed).
                    // Now set the specific CCPA/COPPA flags for LevelPlay, and then continue.
                    // Note: GDPR/TCF string is automatically saved to PlayerPrefs by UMP and read by LevelPlay.
                    SetLevelPlayPrivacyFlagsAndContinue(onComplete);
                });
            });
        }

        private static void SetLevelPlayPrivacyFlagsAndContinue(Action onComplete)
        {
            // LevelPlay automatically reads the TCF v2 string generated by Google UMP from PlayerPrefs.
            // So we DO NOT need to manually call LevelPlayPrivacySettings.SetGDPRConsents() anymore.
            
            // However, we should still explicitly handle CCPA (California) and COPPA (Children).
            // false = user has NOT opted out of sale of personal info.
            LevelPlayPrivacySettings.SetCCPA(false); 
            // false = app is NOT directed to children.
            LevelPlayPrivacySettings.SetCOPPA(false);

            // Now that consent is resolved, trigger the callback to initialize SDKs
            onComplete?.Invoke();
        }
    }
}
